unaligned_nt_ext:
    # file extension for unaligned nucleotide files
    "_unaligned.nt.fasta"

unaligned_aa_ext:
    # file extension for unaligned amino acid files
    "_unaligned.aa.fasta"

protein_directory:
    # directory where unaligned proteins are
    "test_data/"

group_file:
    # Clusters from PopCOGenT
    "test_data/test_clust.csv"

group_type:
    # The groups you want to use to define within- vs. between- group dn/ds. 
    # Main_cluster corresponds roughly to species-level groups, i.e., completely disconnected groups in a gene transfer network.
    # Cluster_ID corresponds to population-level clustering (more fine-grained) 
    "Main_cluster"

output_directory:
    #Directory for pipeline outputs. Will be created if it does not already exist
    "test_output/"